# goal of this is to be very fast and only protect from committing a crime, like pushing secrets or committing to main
# ci will fix formatting and run other checks when a PR is created
# note that all scripts are local, avoiding 3rd party vulnerabilities
repos:
- repo: local
  hooks:
  - id: check-secrets
    name: check for committed secrets
    entry: python3 scripts/pre_commit_hooks/check_secrets.py
    language: system
    stages: [pre-commit, pre-push]
    types: [text]
    args: ["--ignore-yaml-keys=authSecret", "--exclude-files=uv.lock"]
  - id: prevent-protected-branch
    name: prevent direct commits and pushes to main
    entry: python3 scripts/pre_commit_hooks/prevent_protected_branch.py
    language: system
    always_run: true
    pass_filenames: false
    stages: [pre-commit, pre-push]
  - id: check-added-large-files
    name: check for large files
    entry: python3 scripts/pre_commit_hooks/check_large_files.py
    language: system
    args: ["--maxkb=500"]
