apiVersion: v2
name: mcp-kubecost
description: FinOps MCP server for Kubecost analytics.
type: application
version: 0.13.0
appVersion: "0.13.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/kubecost/mcp-kubecost
sources:
  - https://github.com/kubecost/mcp-kubecost
keywords:
  - kubecost
  - finops
  - mcp
icon: https://raw.githubusercontent.com/kubecost/.github/9602bea0c06773da66ba43cb9ce5e1eb2b797c32/kubecost_logo.png
