{{- if include "mcp-kubecost.persistenceEnabled" . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mcp-kubecost.oauthStorageClaimName" . }}
  labels:
    {{- include "mcp-kubecost.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  {{- with include "mcp-kubecost.storageClass" . }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
